/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoEspera.java
 *
 * Created on 02/04/2012, 02:45:56 PM
 */

package com.develcom.gui;

import java.awt.Color;
import org.apache.log4j.Level;
import com.develcom.gui.tools.CentraVentanas;
import com.develcom.tools.trazas.Traza;
import javax.swing.JLabel;

/**
 *
 * @author develcom
 */
public class DialogoEspera extends javax.swing.JDialog {
//public class DialogoEspera extends javax.swing.JDialog implements Runnable{
//public class DialogoEspera extends javax.swing.JInternalFrame implements Runnable{

    private Traza traza = new Traza(DialogoEspera.class);
    public String mensaje;

    public DialogoEspera(String mensaje) {
        setModal(true);
        initComponents();
        jlMensaje.setText(mensaje);
        setBackground(new Color(224,239,255));
        CentraVentanas.centerDialog(this);
//        setVisible(true);
        
    }

    public DialogoEspera() {
    }



    public void mostrar(String mensaje) {
        setModal(true);
        initComponents();
        jlMensaje.setText(mensaje);
        setBackground(new Color(224,239,255));
        CentraVentanas.centerDialog(this);
        setVisible(true);
    }


    public void mostrar() {
        setModal(true);
        initComponents();
        setBackground(new Color(224,239,255));
        CentraVentanas.centerDialog(this);
        setVisible(true);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        barraProgreso = new javax.swing.JProgressBar();
        jlMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Espere, por favor...!!!");
        setBackground(new java.awt.Color(224, 239, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        panel.setBackground(new java.awt.Color(224, 239, 255));

        barraProgreso.setIndeterminate(true);
        barraProgreso.setString("");

        jlMensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMensaje.setText("Espere...");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    public JLabel getJlMensaje() {
        return jlMensaje;
    }

}
